### ISSUE TITLE
Errors encountered. Game not started

### ISSUE THREAD

**Issue by hoi3sfer** [KC3Kai/KC3Kai#1316] opened 2016-04-23 07:58 UTC
chrome-extension://hkgmldnainaglpjngpajnnjfhpdjkohh/assets/css/bootstrap.css Failed to load resource: net::ERR_FILE_NOT_FOUND
managers.js:5 Uncaught ReferenceError: KC3Ship is not defined
global.js:3 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Comment by dragonjet** [comment] 2016-04-23 12:36
you might be using the Legacy theme. Use natsuiro or plain themes.

**Comment by dragonjet** [comment] 2016-04-24 02:48
I just teamviewered someone claiming the same problem. It seems there's a problem with some languages that says `remodelDbGroups` is undefined or something like that. Will take a look at it.

**Comment by woudX** [comment] 2016-04-24 04:00
I also find this problem on latest chrome version(50.0), maybe this bug is caused by bootstrap.css file missing in local cache?

**Comment by sinsinpub** [comment] 2016-04-24 06:52
Reason of `Cannot read property 'remodelGroups' of null`:
`RemodelDb._db` is inited as null, but `Translation.js` checks its existence via `typeof RemodelDb._db!=='undefined'`. And when `remodelDb` attribute is missing in `localStorage`, the loading of `Translation.js` will fail on that checking.

I could send a fix for this, but Ive made the `Translation.js` support 'extend quotes by reusing ship's pre-remodels' for EN too on my branch.
And in this case, quotes loading will be failed to support the extending feature for the 'first game time' (duration of `localStorage.remodelDb` not existed)...  and automatically 'fixed' on next time :joy:

**Comment by Javran** [comment] 2016-04-24 07:04
well, off topic, but I just want to ask is this really necessary to hold so many things in one branch? I don't think this is the first time we run into this kind of mess.

**Comment by sinsinpub** [comment] 2016-04-24 07:45
@Javran it's necessary. if there are so many local branches, I have to merge/rebase so 'mass' for each time master updated. And don't worry about that, I can pick some out and put into another branch when it's necessary.

**Comment by Javran** [comment] 2016-04-24 08:02
@sinsinpub you can keep a local branch or push to your person repo fork. I also hold a local branch for the same reason. I can understand it keeps things easy but when it comes to public repos, you need to make patches small so developers related has a better chance of reviewing it.

so about this issue, i think we'd better keep a default master data somewhere as a fallback so ppl can still use these functions without having to load the game. I've seen a complete piece of master data in our tests/ directory, how about moving it into src/assets and make these modules to load it as a fallback?

**Comment by sinsinpub** [comment] 2016-04-24 08:08
@Javran ofc I do that. the branch at this repo is just for you guys to view or test my current works :smile:  and these works are not just a small patch, it is a 'big' enhancement in fact.

is that possible to build `RemodelDb` from existed `WhoCallsTheFleetDb` when master data is not ready?

**Comment by Javran** [comment] 2016-04-24 08:27
@sinsinpub hmph, you can have your own fork of the repo for putting all your patches together for others to try but if you insist that I don't want to argue.

maybe RemodelDb can be based on WhoCallsTheFleet, but that means another dependency we must rely on. the problem is more general than just RemodelDb, Master.js also needs api_start2 to be fed. I'd prefer solving these 2 problems in one go if it's possible.

**Comment by sinsinpub** [comment] 2016-04-25 20:24
it seems that my PR resolved another issue, but this issue still occurs when play via DMM website.

exception `managers.js:5 Uncaught ReferenceError: KC3Ship is not defined   managers.js:5` screenshot from another reporter: https://i.imgur.com/e7PUPMn.png

**Comment by sinsinpub** [comment] 2016-04-25 20:41
`KC3Ship is not defined` issue sourced from commit 0865d23 of PR #1264 
Possible reason: `web.html`(and js) does NOT need to add `RemodelDb.js` ref, coz it not supposed to support subtitles. And maybe RemodelDb depends on `objects` (KC3Ship.js is one of them), but grunt does not import `library/objects.js` for `web.html`

making another patch for it, and a grunt built version tester needed to verify :sweat_smile:

**Closed** 2016-04-26 11:36 UTC
Labels: type:bug

**Comment by dragonjet** [comment] 2016-04-26 11:39
not sure why this was not closed when PRs were merged but it's included now in Release 29.1 https://github.com/KC3Kai/KC3Kai/pull/1315
