### ISSUE TITLE
Quest translation doesn't work properly

### ISSUE THREAD

**Issue by Arrownymes** [KC3Kai/KC3Kai#2975] opened 2020-04-04 14:27 UTC
### Versions:
-Chrome Versie 80.0.3987.149
- Windows 10 home 1903
-64 bit
- 34.4.4 KC3 plugin costumized DMM page

### Steps to reproduce:
After last maintaince I just had it, I don't know how it happened, but now it's very difficult to continue my quests. Also happens in other tabs!

### Actual behaviour:
![image](https://user-images.githubusercontent.com/58956807/78453250-b73fc780-7690-11ea-90ce-500ef728f21a.png)

### Expected behaviour:
The translation overlay should apply the right translation instead of the same translation from the first page to all quests

**Comment by sorewachigauyo** [comment] 2020-04-04 14:41
Duplicate of https://github.com/KC3Kai/KC3Kai/issues/2966
For now press F10 to clear overlay

**Closed** 2020-04-06 03:35 UTC
Labels: type:duplicate
