### ISSUE TITLE
a empty bug with akashi panel in friday

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#3083] opened 2021-01-28 04:47 UTC
![01](https://user-images.githubusercontent.com/6552290/106091256-fa5eb000-6166-11eb-9db8-052dc0838ec1.jpg)

![02](https://user-images.githubusercontent.com/6552290/106091238-f2067500-6166-11eb-941e-c47cb793b664.jpg)

**Comment by ztjal** [comment] 2021-02-03 08:44
wednesday

![屏幕截图 2021-02-03 164139](https://user-images.githubusercontent.com/6552290/106720978-07840f00-663f-11eb-95e9-8e49aa035038.jpg)

**Comment by sinsinpub** [comment] 2021-02-03 09:56
that's an issue caused by upstream database [WhoCallsTheFleet](https://github.com/TeamFleet/WhoCallsTheFleet), not sure why he has removed items from `sun` to `thu`
![image](https://user-images.githubusercontent.com/160240/106729683-bb3dcc80-6648-11eb-8ab8-8d881413960e.png)

expected should be
![image](https://user-images.githubusercontent.com/160240/106729726-c8f35200-6648-11eb-9d15-7f831b5ab4be.png)
![image](https://user-images.githubusercontent.com/160240/106729771-d6a8d780-6648-11eb-9a3d-8b08d8091e61.png)

it should be reported to [the project](https://github.com/TeamFleet/WhoCallsTheFleet/issues) or its [submodule](https://github.com/TeamFleet/WhoCallsTheFleet-DB/issues)

**Comment by Diablohu** [comment] 2021-02-05 15:05
Thanks for the report. A update for WCTF database is on the way.

**Comment by Diablohu** [comment] 2021-02-05 19:21
fixed in https://github.com/TeamFleet/WhoCallsTheFleet-DB/commits/master

**Closed** 2021-02-05 22:31 UTC
Labels: area:data, type:update-adjustment
