### ISSUE TITLE
extension causes chrome to become unresponsive

### ISSUE THREAD

**Issue by Verniy99** [KC3Kai/KC3Kai#1826] opened 2017-02-14 06:59 UTC
ive had KC3Kai for almost 2 years now and i notice that with the latest update that it causes Chrome to become unresposive. ive had to uninstall and re-install Chrome 3 times now because if it. i love using KC3 because it make kancolle so much easier but untill its fixed i have to remove the extension.
 Chrome 56.0.2924.87
windows 8.1
KC3 30.0.6

**Comment by mikenzb** [comment] 2017-02-14 07:03
What chrome version and OS are you using?

**Comment by nonsensed** [comment] 2017-02-14 07:03
@Verniy99 You did not fill out the template when you opened this issue. We need more specifics if we are to resolve this issue. "Become unresponsive" is not helpful.

**Comment by Verniy99** [comment] 2017-02-14 07:05
i added the versions. and chome freezes and i have to foce shut it down. i become unabe to use chrome at all.

**Comment by mikenzb** [comment] 2017-02-14 07:21
What game mode do you play with? because noticed much higher ram usage playing via DMM Website with the new customizations as well.

Does playing via DMM iframe (old) or API still work for you?

**Comment by sinsinpub** [comment] 2017-02-14 07:33
if you are using API Link mode or DMM Frame mode, could you do me a favor to test if chrome freeze or not by: disabling subtitles, quest overlays, idle timer via settings.

**Comment by Verniy99** [comment] 2017-02-15 06:10
i was using the new play on DMM option when i first notice it. tried using the old dmm iframe and ended up with the same result.

**Comment by dragonjet** [comment] 2017-02-16 09:10
shouldn't be caused by new game mode. when it was reported, kc3 version was 30.0.6 which still didn't have chrome version.

@Verniy99 have you tried disabling the extension and playing normally via DMM website?

**Comment by nonsensed** [comment] 2017-02-17 19:31
Possibly related, but there is no useful information to be gained from it as of this writing:

[reddit](https://www.reddit.com/r/kancolle/comments/5ujzth/help_memory_usage/)

(more of a "it seems like other users are also experiencing this" comment than anything else)

**Comment by mikenzb** [comment] 2017-03-21 06:40
I'm going to close this as my chrome memory leaks were fixed in version 57 of chrome, reopen if issue still persists.

I believe it was fixed with [this](https://chromium.googlesource.com/chromium/src/+/e724b2c3898091f20dd9e9c302cb12c86cdf5e5f) chromium commit which is now on the stable channel of chrome so just make sure your chrome is up to date.

**Closed by mikenzb** 2017-03-21 06:40 UTC
