### ISSUE TITLE
API error when enter night battle node

### ISSUE THREAD

**Issue by Natsu-kun** [KC3Kai/KC3Kai#1587] opened 2016-11-04 12:16 UTC
Versions:
OS: Windows 10 Pro AU 64bit
Chrome: 54.0.2840.87 m (64-bit)
Extension: 30.10.3

Steps to reproduce:
- Enter night battle node at world 4-5

Screenshots :
![screenshot 2016-11-04 19 04 19](https://cloud.githubusercontent.com/assets/7970907/20005138/027866e4-a2c3-11e6-8e5e-914df0c94d35.png)

**Comment by Iksapalif** [comment] 2016-11-04 13:32
Can confirm, it happened with the night battle node on 2-5 too.

**Comment by Tamachan12** [comment] 2016-11-04 19:30
Yes it happens on 2-5 Node D as well

**Comment by Javran** [comment] 2016-11-05 01:08
I believe this happens on every night battle node, some console output:

![2016-11-04_210406_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/20026528/46f7cc38-a2d2-11e6-823b-58b32a9b1dac.jpg)

also I suspect the bug is introduced after commit f6affa09

**Comment by sinsinpub** [comment] 2016-11-05 02:23
it's caused by commit 017dec3b110c39f67199490dca41147168bbdaa1
new `maxHPs` is also required to be defined for `engageNight` in `Node.js`, but I'm not sure why `originalHPs` is no longer to work? 😓  if so, `originalHPs` is not used any more, could be removed.

**Comment by dragonjet** [comment] 2016-11-06 02:27
ah wait, I have a fix for this since yesterday or last Friday, I just haven't pushed it

**Closed** 2016-11-06 06:21 UTC
Labels: type:bug
