### ISSUE TITLE
www.dmm.com didn't send any data

### ISSUE THREAD

**Issue by Adramech** [KC3Kai/KC3Kai#1636] opened 2016-11-28 01:43 UTC
Chrome version: 54.0.2840.99
 Windows 7 ultimate service pack 1
 32bit
 KC3 Kai version: 30.11.3
 I use the version from the chrome store

When the fall event started i tried login in to complete some dailyes but when entering the game from the extension it gave me the message www.dmm.com didn't send any data, refreshing the page solved this and I started playing but since then I get random "cat bombs" in any sort of action wether its resuppling, sending expeditions or sorting. I've already cleared the cache, the cookies, reinstalled chrome , run the antivirus, restaring the modem and calling the ISP but nothing works. I tried entering dmm with mozilla and it seems to work just fine (I could't play though)

**Comment by dragonjet** [comment] 2016-11-29 03:46
can you try to load it via chrome, but this time, not though kc3 gameplay options, just the [regular game link](http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/). This is so that we can test if it's a chrome problem, or if it's something we can fix on kc3 side.

**Comment by dragonjet** [comment] 2016-12-04 23:00
duplicate of #1600

**Closed by dragonjet** 2016-12-04 23:00 UTC
Labels: duplicate
