### ISSUE TITLE
[bug report]sortie debriefing interface show mvp gained but ship that isn't sorting

### ISSUE THREAD

**Issue by c933103** [KC3Kai/KC3Kai#84] opened 2015-05-16 16:39 UTC
See imgur.com/ee36fnk

**Comment by Crazyteitoku** [comment] 2015-05-16 19:39
Is that supposed to be Ashigara right next to the S ranking?. If so that is not the ship that got MVP but that is the drop that you got from completing that node.

Also in the future you might want to consider looking at using the likes of (https://gyazo.com/) for doing screenshots that are from within developer console window for instance.

**Comment by AlanSchaeffer** [comment] 2015-05-17 00:19
I also found it strange at first, but soon after analyzing larger amounts of data I figured it out. Could it be considered to have some form of documentation in there to say it is the dropped ship? Like a tooltip text on the image.

**Comment by c933103** [comment] 2015-05-17 02:14
but there were no ship slot left at that time, thus the drop was not obtained...

**Comment by Crazyteitoku** [comment] 2015-05-17 04:27
Initially I tested the newly revamped "sortie log" (this was actually before KC3 Kai v008 was pushed into Google WebStore) and whilst consulting with Dragonjet via chat I too was confused at first but I am certain Dragonjet confirmed that this feature is drops and not for the ship that got MVP as it would have made no sense if that ship was never in the fleet in the first place.

@AlanSchaeffer I am unsure if there are any indications that such icon is a ship dropped from that node. However I agree that we could suggest it as a feature request. Even more so is that this extension in general lacks decent documentation.

@c933103 I am certain that this would be the reported ship to drop had you not have any ship slot(s) left. 

There are no other possibilities and presumably the information was caught passively and not "randomly guessed" to be the ship to drop. For this case to be considered as a bug I would recommend you proving through alternative means that the ship icon as mentioned was actually a different ship that was dropped at that time. In order for that happen you need to make sure that you have spare ship slot(s).

**Comment by dragonjet** [comment] 2015-05-18 16:32
yes that was supposed to be the drop, though C9's problem should also be possible.

The API might be **always** returning the drop regardless of slots, which unfortunately also **always** saved by the app... but who knows maybe on the server side it actually did the ship-slot check before adding it on your list.

will try this myself sometime

**Comment by Crazyteitoku** [comment] 2015-09-17 00:55
Closing this issue because I believe there is no real need to chase up on it.

If it was actually a bug then the only possibility to avert that would be to not show the ship faces because one's slots are already full.

**Closed by Crazyteitoku** 2015-09-17 00:55 UTC
Labels: enhancement, help, other
