### ISSUE TITLE
[Mega Thread]RredderR's found devbugs

### ISSUE THREAD

**Issue by RredderR** [KC3Kai/KC3Kai#753] opened 2015-09-04 14:04 UTC
NOTE*: I'll regularly update this thread of mine whenever I find a new bug of KC3 Kai dev

**Comment by McDohl** [comment] 2015-09-04 15:37
it's not a bug =_=
this is popup....
![image](https://cloud.githubusercontent.com/assets/13024936/9687770/6eaf413e-5355-11e5-80e2-458d91ab04cc.png)

**Comment by RredderR** [comment] 2015-09-05 00:31
I'm not stupid, dude. But instead of that popup. I really get the No webpage was found for the web address: chrome-extension://idbggmjaomlpadegpehiclokcfagijkj/pages/popup/popup.html
Also, the extension's gone now o_o Guess I'll put it back and try it again.

**Comment by RredderR** [comment] 2015-09-05 00:33
Working now. I'll update my list.

**Comment by bamboo3250** [comment] 2015-09-05 03:40
I tried doing that and it works for me. Mine is github version.

![screen shot 2015-09-05 at 11 38 01 am](https://cloud.githubusercontent.com/assets/8078323/9697508/ca51e420-53c2-11e5-97c1-253a552985cb.png)

**Comment by ethrundr** [comment] 2015-09-07 09:47
One suggestion, since you've started the same way like I used to do when I first join this project.
Instead of reporting all the found bug here in one thread, just keep opening new thread for all bugs you found. That way the coder can easily address and assign each problem~

**Comment by Crazyteitoku** [comment] 2015-09-17 01:19
Closing issue, and I agree at what @ethrundr said. Even I started a similar way as well - by combining suggestion and bug report in one thread.

**Closed by Crazyteitoku** 2015-09-17 01:19 UTC
