### ISSUE TITLE
战略指挥室 的 活动图联合战斗记录与面板战斗评级掉落

### ISSUE THREAD

**Issue by nagatoyk** [KC3Kai/KC3Kai#1046] opened 2015-11-19 00:57 UTC
如题, 联合舰队战斗评级和掉落均不能正常工作, 还有战略指挥室的活动图战斗记录不能正常工作 稍后补图

补图1:
![补图1](http://ww1.sinaimg.cn/large/64909e84jw1ey60dqhlhtj20ft0cstcy.jpg)

补图2:
![补图2](http://ww3.sinaimg.cn/large/64909e84jw1ey60l0319fj20vt0kywk6.jpg)

**Comment by Javran** [comment] 2015-11-19 01:56
唔,我在忙别的事,暂时还没开始打. 另外希望开issue还是用英文.... 否则其他开发者可能就看不懂了.

**Comment by Javran** [comment] 2015-11-19 02:03
For other developers that can't read Chinese:

@nagatoyk said battle rank for combined fleet and ship drop doesn't show up. Also battles are not recorded in strategy room.

**Comment by dragonjet** [comment] 2015-11-19 09:14
ah I mentioned this on gitter, and is a legit bug, separate from the new combined fleet prediction bug

I checked and this happens to all combined fleets, but not single fleets

```
this.lostShips = [resultData.api_lost_flag,resultData.api_lost_flag_combined || [-1,0,0,0,0,0,0]]
            .map(function(lostFlags,fleetNum){
```

seems `lostFlags` is undefined

and is probably the cause for the battle rank and ship drop not showing up, and also being not recorded on history. i think when it encounters this error, all other executions in the result screen (rank, drop, history) are stop and skipped

I'll be adding the Fall event tab on strategy room though. The sorties are still recorded, but those that encountered the error mentioned above will have no nodes, like this

![](http://puu.sh/lqWTH.jpg)

**Comment by nagatoyk** [comment] 2015-11-19 09:42
That the solution of the problem depends on how?

**Comment by dragonjet** [comment] 2015-11-19 10:29
still not sure, tagging @ReiFan49 here XD

**Comment by ReiFan49** [comment] 2015-11-19 12:04
1. battle might be not recorded because there's an error that related to ship drop
2. haven't checked with combined battle (focusing on lodger)

**Comment by dragonjet** [comment] 2015-11-19 12:48
Fixed as of https://github.com/KC3Kai/KC3Kai/commit/6cf8a989930f3011c7f6334b42709ccd7c927158

**Closed by dragonjet** 2015-11-19 12:48 UTC
