### ISSUE TITLE
Resources usage counter for event map

### ISSUE THREAD

**Issue by lott10** [KC3Kai/KC3Kai#1009] opened 2015-11-05 08:33 UTC
you know logs for fuel, buckets, bauxite and all that you use in event map
~~so you can see how your exped DDs' blood, sweat and tears down the drain just like that~~

**Comment by dragonjet** [comment] 2015-11-05 10:10
though we already have resource graph on strategy room? I'm thinking just remember the date/time when a player started and ended a map to track it on the graph

**Comment by lott10** [comment] 2015-11-05 12:50
but that way it will also count resource gained from expedition during that time, have to take out reso gained first
that's how I do it all this time, guess it'll be easier now that we have expedition history

I used to take notes of my expedition resut in notepad lol

**Comment by LostLogia4** [comment] 2015-11-06 01:05
Currently in [development hell](https://github.com/KC3Kai/KC3Kai/issues/809).

**Comment by ethrundr** [comment] 2015-11-06 01:59
@dragonjet in my opinion, to facilitate this, how about if we lock the graph duration (maybe the monthly one) into one month from the event starts for each event, since most of the time we will do update during the start and the end of each event.

Upon event ends, the lock to the graph will be lifted and it'll be like usual: the start and end date updated per day for the monthly graph.

At least we can do this until the configurable graph in previous thread is completed and implemented.

**Comment by dragonjet** [comment] 2015-11-06 02:00
hm that's a good idea

**Comment by LostLogia4** [comment] 2015-11-06 02:07
@ethrundr configurable graph? But the one in my thread is a ledger, was it not?

**Comment by dragonjet** [comment] 2015-11-06 02:14
but I thought that thread was for break-down. This one will not break-down the in-out sources but only limit the time span of graph from Nov. 18 to let's say Dec. 9

**Comment by lott10** [comment] 2015-11-06 02:42
a separate graph with your initial resource that will only go down?
that works too

I only  take notes of resource in event, but #809 looks neat :open_mouth:

**Comment by LostLogia4** [comment] 2015-11-06 13:17
@dragonjet You kinda lost me there, I'm asking ethrundr whether he's mistaking my ledger for a graph.

@lott10 Don't you think so? After all, resource management and logistics aren't really that much different from accounting. Especially for quantized in-game resources like fuels and steels and whatnot.

**Comment by dragonjet** [comment] 2015-11-06 23:24
ah so that's why your username is LostLogia4 jk :laughing: anyway I got lost there too. So this is duplicate of #1009?

**Comment by LostLogia4** [comment] 2015-11-07 01:21
@dragonjet Not really. It's more like a lite version of the ledger actually. But then again a modular approach might be better considering the development hell it had gone through...

**Comment by ethrundr** [comment] 2015-11-07 02:49
@LostLogia4 ah, I see :laughing: kinda lost as well lol

**Comment by ethrundr** [comment] 2015-11-07 02:52
@LostLogia4 lol, it seems I mixed up between your Ledger and my own suggestion in #420 :laughing:

**Comment by LostLogia4** [comment] 2015-11-07 05:43
@ethrundr Actually, it might be possible to have both, assuming the underlying DB was built.
@ReiFan49 had worked on it but I haven't heard of the progress since.

**Comment by ethrundr** [comment] 2015-11-13 08:18
better to call him so he may report his progress
@ReiFan49

**Comment by ReiFan49** [comment] 2015-11-13 14:31
![image](https://cloud.githubusercontent.com/assets/9847780/11148186/d02f0bea-8a4d-11e5-95d2-512ac91d88cd.png)
still attempting to count regeneration for now

**Comment by LostLogia4** [comment] 2015-11-13 14:48
Mayanaka at ttk Level 2 :laughing:

**Comment by dragonjet** [comment] 2017-02-16 09:42
ledger + the updated graph filters should do the trick. re-open or create new thread if there are follow-up suggestions

**Closed by dragonjet** 2017-02-16 09:42 UTC
Labels: type:discussion
