### ISSUE TITLE
API_Req BUG

### ISSUE THREAD

**Issue by Hashtagwolfie** [KC3Kai/KC3Kai#2322] opened 2017-11-17 21:23 UTC
### Versions:
- Chrome version 62.0.3202.94
- Window 7 Ultimate Service Pack 1 64 bit
- KC3 version 31.11.10
- https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh

### Steps to reproduce:
- Delete all cache and historia of Chrome
- Run KC3 and do a sortie

### Actual behaviour:
- Red note or message on Kancolle tab about API error

### Expected behaviour:
- Red note or message on Kancolle tab about API error
- Lots of API message everytime you go to dock, sortie, fleet,...

### Screenshots (if applicable):
![capture](https://user-images.githubusercontent.com/33765302/32969439-71fca268-cbe5-11e7-92bf-b65d53fb7038.PNG)

### Error Report (if applicable):
[KC3-Error-1510953624.txt](https://github.com/KC3Kai/KC3Kai/files/1483884/KC3-Error-1510953624.txt)
[KC3-Error-1510953690.txt](https://github.com/KC3Kai/KC3Kai/files/1483885/KC3-Error-1510953690.txt)
[KC3-Error-1510953723.txt](https://github.com/KC3Kai/KC3Kai/files/1483886/KC3-Error-1510953723.txt)
[KC3-Error-1510953749.txt](https://github.com/KC3Kai/KC3Kai/files/1483887/KC3-Error-1510953749.txt)
[KC3-Error-1510950816.txt](https://github.com/KC3Kai/KC3Kai/files/1483888/KC3-Error-1510950816.txt)

**Comment by mikenzb** [comment] 2017-11-17 21:54
Duplicate of #2318

**Closed by mikenzb** 2017-11-17 21:54 UTC
