### ISSUE TITLE
API Link breaking upon browser refresh

### ISSUE THREAD

**Issue by HydraGoliath** [KC3Kai/KC3Kai#1200] opened 2016-03-19 06:41 UTC
API links break when the browser is refreshed even if they haven't actually expired yet. They were working fine before version 27 released.

**Comment by dragonjet** [comment] 2016-03-19 06:57
unfortunately, v27 was published to the webstore accidentally - it should've been a draft only and I haven't really tested it. sorry, will work on it this weekend to sort things out with 27

**Comment by sinsinpub** [comment] 2016-03-19 14:06
I don't think it's a bug. Play via API changes indeed, new API link will be refresh inside the extension page without open another tab after accessing DMM official page. There's nothing 'being broken', but remember to configure your adblock or something, let it allow our extension to acess DMM url (dmm frequently added as a rule of ad source)

and the hotfix for 27.2 not work yet: 
* Game size not applied as config
* Game not start even switched to kancolle tab

**Comment by dragonjet** [comment] 2016-03-19 14:33
this should've been fixed in 27.3 https://github.com/KC3Kai/KC3Kai/pull/1201

I can confirm it's broken. Lots of reports over social media over this. They say "Pay via API Link" is drunk. Even I got left mouth-hanging when I went through the experience. It's not just the flow of refreshing API Link. the fact that it gave me an invalid page not even in 5 mins after getting a link - something's wrong right there. And refreshing will sometimes get you to the page without the game frame in the middle - just the box container with background. I couldn't even explain what else went wrong. I reverted everything I didn't know about on the API page. We can think about re-implementing them (Idle timers, expire whatsoevers) one by one checking which causes the errors.

**Closed by dragonjet** 2016-03-19 14:33 UTC
Labels: bug

**Comment by dragonjet** [comment] 2016-03-19 14:35
@sinsinpub the "Game not start even switched to kancolle tab" should be fixed on 27.4, while the gameplayer scale seems to be not applied at all in the page. I remember in my mind this really was implemented before, not sure what happened :sweat_smile:
