### ISSUE TITLE
Error problem

### ISSUE THREAD

**Issue by Saval130** [KC3Kai/KC3Kai#1917] opened 2017-03-24 12:49 UTC
- Your Chrome version - 56.0.2924.87
- Windows
- 32bit
- KC3 Kai version - 31.2.0

So, after updating to the newest version I tried to play the game, only to get an error message that won't go away.  It doesn't seem to load at all.  Here is the message:

Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at global.js:4
    at global.js:4
(anonymous) @ global.js:4
(anonymous) @ global.js:4
objects.js:4 KC3改 Messengers loaded

Anyone know what this is or how to fix it?

**Comment by Nya-chan** [comment] 2017-03-24 14:17
> It doesn't seem to load at all.

What does it mean exactly? White screen? Black screen?
Can you see the DMM page or KC3Kai loading screen?
Is your version from store or development?

**Comment by ethrundr** [comment] 2017-03-25 03:55
@Saval130 may I ask you to try reproducing the same error and take a screenshot out of it?

This way, we can address the error more accurate and gives a better solution to you.

**Comment by Saval130** [comment] 2017-03-25 11:12
![screenshot](https://cloud.githubusercontent.com/assets/26650684/24321720/b26e8d4a-1121-11e7-8f82-20b5a7ab1db0.jpg)

Here's the screen.  And I think my version is development.

And this happens every time I go to start the game.  It never gets past this.  I click on the command center, hit F12, and click the Kancolle tab.  Then I get this screen and nothing else.

**Comment by DynamicSTOP** [comment] 2017-03-25 12:48
Dev version has different icon in toolbar and different tab name.

This error shouldn't block your from playing.
![default](https://cloud.githubusercontent.com/assets/9434504/24322278/c06c2172-1168-11e7-9a40-30ca0dcaa97b.png)

Could you reveal what do you have under Elements tab? 
![default](https://cloud.githubusercontent.com/assets/9434504/24322323/0fc2470a-116a-11e7-8831-b48406920ac9.png)
I assume game isn't loaded because page content is blocked for some reason. If you have adblock or something like that, please add dmm.com to it's exception list.

**Comment by gensuihime** [comment] 2017-03-25 14:49
Do you have any extension(s) that blocks the running of scripts and/or Shockwave Flash objects (.swf)?
Things like ScriptSafe or NoScript, or even adblockers are known to stop the execution of flash objects. Please check if you have any of these applications and add DMM.com to the whitelist (allow them to run) or disable these extensions when playing.
![block](https://cloud.githubusercontent.com/assets/11739276/24323200/5a86d6ea-1140-11e7-8919-39debef695ef.png)

**Comment by DynamicSTOP** [comment] 2017-03-25 16:21
@gensuihime if you want to add tags, please read the following https://github.com/KC3Kai/KC3Kai/issues/1730

**Comment by gensuihime** [comment] 2017-03-25 16:42
@DynamicSTOP No documentation for tags, and makes it actually kindof hard to understand reading tags.

If you go ahead and adhere every single issue (I count 194 open) to #1730  tag system, Yes I will follow. Otherwise, pls give me a good reason not to make tags actually legible.

**Comment by Nya-chan** [comment] 2017-03-25 16:57
> Otherwise, pls give me a good reason not to make tags actually legible.

Your tags are actually _less_ legible, because they are all over the place. I won't search "Not working" under "I-It's not working" and separating them under type, status or area has big advantage of searchibility and easily seeing that you can pick 2 - 3 types of tag for an issue / PR.

**Comment by Saval130** [comment] 2017-03-26 10:01
Here's the screenshot you requested!

![screenshot 3](https://cloud.githubusercontent.com/assets/26650684/24330315/42851ace-11e1-11e7-8e3c-c6c7d3838999.jpg)

**Comment by Vultren** [comment] 2017-03-30 23:00
@Saval130 have you tried going to the site without the command center? Trying to check off points of failure

**Comment by Saval130** [comment] 2017-03-31 12:34
I did, and it sends me instead to Nutaku.net where I cannot find the game.

**Comment by Nya-chan** [comment] 2017-03-31 12:35
Switch your language to Japanese - the game isn't available on the English copy.

**Comment by Saval130** [comment] 2017-03-31 12:36
At that point I won't be able to understand a thing on it though...

**Comment by Saval130** [comment] 2017-03-31 12:42
Nope, apparently I am too Gaijin to be allowed to play it...  It's not enabled for foreign players through the normal site.

**Comment by Nya-chan** [comment] 2017-03-31 13:42
> At that point I won't be able to understand a thing on it though... I'll try though

If it had English version, there wouldn't be any point in having KC3Kai translation overlays in the first place :) It was always this way.

Switch language to Japanese on the homepage (dmm.com), then go into KC3Kai settings and check "Force Cookie Hack" and try launching it via the extension (in your browsing you might've messed up your cookies somewhere). If it works, don't forget to uncheck the cookie hack in the settings later.

It might also help if you set your time and timezone to Japanese when you log in for the first time.

**Comment by Saval130** [comment] 2017-03-31 17:15
Thank you!

**Comment by Nya-chan** [comment] 2017-04-01 22:55
Seems fixed, so closing

**Closed by Nya-chan** 2017-04-01 22:55 UTC
Labels: type:help
