### ISSUE TITLE
graphic error!!!!!

### ISSUE THREAD

**Issue by blizzardpotato** [KC3Kai/KC3Kai#2036] opened 2017-05-07 03:11 UTC
Please make sure that you have these details on hand when submitting your issue/bug report as this will greatly speed up the issue triage process -- thank you!

- Your Chrome version - via chrome://version/ - chrome/31.6.2
- Your OS and its version - win8
- 32bit or 64bit? - 64bit
- Your KC3 Kai version - via chrome://extensions/
- Which build you have tried running? webstore version as in the one from [Chrome Web Store](https://chrome.google.com/webstore/detail/kancolle-command-center-%E6%94%B9/hkgmldnainaglpjngpajnnjfhpdjkohh) or Github variant (better known as developer builds).
- Which game play mode you are using? -[ dmm direct play]
- Screenshots which accurately paint the issue(s) you are facing. 
- A step by step method that you did to describe how you got to that issue.
- A KC3 Error Report JSON file if you have faced an API error. To upload it, you might append `.txt` as file name extension.

After reading previous part of instruction, you can safely remove them now (including this line). Then fill up following part with your situation.

### Screenshots (if  #applicable):
![2017-05-01 14-40-23 62](https://cloud.githubusercontent.com/assets/28183501/25777619/8b05f388-331d-11e7-8740-1fa0e19517d4.jpg)
![2017-05-01 14-43-09 76](https://cloud.githubusercontent.com/assets/28183501/25777620/8b0ace6c-331d-11e7-807b-4fa6d782d19d.jpg)

this error is so frequent

I report this error a month ago, but ignored this report

I'm playing only kc3

Because of this error, my event screenshot was ruined!! :(

please resolve this error.

Thank you.

**Comment by mikenzb** [comment] 2017-05-07 05:17
Hi there, 

I'm sorry you seem to be having issues with KC3, can you please confirm what version of chrome you are using by going to the URL `chrome://settings/help` 

Also if this error when you are taking screenshots or playing the game?

**Comment by blizzardpotato** [comment] 2017-05-07 06:52
My chrome version is 58.0.3029.96 (64-bit)

The lastest version.

This error occurred playing the game.

**Comment by mikenzb** [comment] 2017-05-07 14:01
Can you try playing kancolle on the DMM website without KC3 open to see if you can replicate the same issue.

To do so just make sure the `Apply Customizations` is off and click on `or start without info panel` in the bottom right.

**Comment by Vultren** [comment] 2017-05-07 18:01
adding the duplicate tag as this is the same issue blizzardpotato put up a week ago ( #2004).

**Comment by Vultren** [comment] 2017-05-19 15:37
@blizzardpotato did you try without the customization turned off?

**Comment by blizzardpotato** [comment] 2017-05-22 13:09
@Vultren  I think this error occurred only event map.
In the general sea area Sometimes an error occurs .

**Comment by blizzardpotato** [comment] 2017-05-23 01:50
@Vultren  Today graphic error occurred at home port!!

oh.. I want to keep using kc3...

please fix it...

other viewer are no error occurs (74 electric observer, abmiral viewer)

**Comment by blizzardpotato** [comment] 2017-05-23 02:19
@Vultren  customization turend off play is no error ocurred.

**Comment by Vultren** [comment] 2017-05-23 04:10
While the kc3 panel is up, when the problem comes up again, do a screen shot of the entire browser not just the game screen

**Comment by ethrundr** [comment] 2017-05-23 04:51
Applying `type:duplicate` on #2004 and removed one here.

@blizzardpotato if possible, please also include the screenshot of the console tab in the panel.

**Comment by TTKAegis** [comment] 2017-05-23 23:47
Glad I'm not the only one seeing this issue. It started about half way through the Spring event and is still happening now. As best I can tell, it only happens after the results screen closes. In event it was happening between nodes, usually before the boss node. Now it's happening after the results page when you return to port. When it happens is random. I was grinding 3-2 for hours without it, and other times getting it every 15 minutes or so. Only option is to reload the game to fix it.

Can confirm it happens on Chrome Version 58.0.3029.110 (64-bit) and the release immediately before that one.

**Comment by mikenzb** [comment] 2017-05-24 06:49
If we could get a screenshot of the `console` tab with the graphic error that would be nice, also a console tab from the KC3 panel by undocking the panel and pressing CTRL+SHIFT+I and going to `console` there as well.

You should have something like this
![capture](https://cloud.githubusercontent.com/assets/5982780/26390204/a65dd082-40b1-11e7-870c-0ecaf167ff5d.PNG)

**Comment by DynamicSTOP** [comment] 2017-05-24 07:28
@blizzardpotato @TTKAegis 
Could you guys post your flash versions? You should be able to find them here
like so chrome://version/
![default](https://cloud.githubusercontent.com/assets/9434504/26391416/5aeb34e6-406b-11e7-9ec0-45e2905b246b.png)
You can cover your profile name in path if you want, but please include everything else from that path.

**Comment by TTKAegis** [comment] 2017-05-25 00:51
Okay, here's what I could get of the error and the flash versions. 

Either hitting CTRL SHIFT I or changing the KC3 window to dock at the side actually fixed the graphics back to normal without reloading the game. I'm not sure which. I'll see which one unscrambled the graphics next time it happens. 

Also, unlike my previous post. this time it scrambled right after starting the game on the results of a fleet returning from expedition. Hadn't seen it scramble on that screen change before. And yes my KC3 is up to date.

<img width="910" alt="error1" src="https://cloud.githubusercontent.com/assets/28910582/26431436/a3711f1c-40c2-11e7-8913-7d2ceee81aa7.PNG">
<img width="911" alt="error2" src="https://cloud.githubusercontent.com/assets/28910582/26431435/a36abd84-40c2-11e7-92a7-82e4c7b0ee6c.PNG">
<img width="371" alt="flash" src="https://cloud.githubusercontent.com/assets/28910582/26431434/a35d7552-40c2-11e7-9e8c-753e9f2bc174.PNG">

**Comment by blizzardpotato** [comment] 2017-05-27 02:15
@mikenzb 
Thanks for your service 
My kc3 client error reoccurred at 5-5
this photo is my flash version and error report
![ddddd](https://cloud.githubusercontent.com/assets/28183501/26517156/bc901770-42cd-11e7-99ab-eae24bb5e8fb.JPG)
![ddds](https://cloud.githubusercontent.com/assets/28183501/26517155/bc8c1440-42cd-11e7-8987-4129c420aed1.JPG)

**Comment by blizzardpotato** [comment] 2017-05-27 12:56
@Vultren 
![11](https://cloud.githubusercontent.com/assets/28183501/26521594/49c22b20-4327-11e7-9b4a-39c49b4828a1.JPG)
![22](https://cloud.githubusercontent.com/assets/28183501/26521595/49ebeffa-4327-11e7-947e-eb6ca63e8d8f.JPG)

**Comment by dsota** [comment] 2017-06-04 01:55
I've been running into this same issue when I'm try to play Kancolle on my laptop. I've even done a complete reinstall of Chrome on my laptop, but the problem still seems to persist. I didn't happen to get a screenshot of my console tab the last time it happened.

![image](https://cloud.githubusercontent.com/assets/18238488/26758253/d712ecb0-48a6-11e7-9543-472390ff3a78.png)
![image](https://cloud.githubusercontent.com/assets/18238488/26758254/ec2a7f1e-48a6-11e7-93a2-5bebf6ce71c1.png)

I've been playing Kancolle on my desktop and laptop and I haven't notice this same issue showing up on the desktop, it only happens when I am playing on my laptop.

**Comment by mikenzb** [comment] 2017-06-04 08:01
To all the people that have been having this issue, can we get you to enable this flag below to see if the issue is fixed. - 
![unknown](https://cloud.githubusercontent.com/assets/5982780/26759921/576ed8d8-4960-11e7-9120-66747ea276b5.png)
@blizzardpotato @TTKAegis @dsota 
You can do so by going to `chrome://flags/#slimming-paint-invalidation`

**Comment by dsota** [comment] 2017-06-08 02:39
@mikenzb I've set Slimming paint invalidation to Enabled and for the past couple of days I have been playing on my laptop the same amount for time I normally do. I did not clear my cache or anything else with my browser.

So far, I have not seen these graphic issues show up since I changed that setting. If anything changes I will update this post with more info

**Comment by mikenzb** [comment] 2017-06-28 21:33
Can anyone here test by turning hardware acceleration off in chrome to see if it helps? 
settings > advanced > system
![capture](https://user-images.githubusercontent.com/5982780/27661292-dc680c98-5cad-11e7-8f30-efe3aa95e012.PNG)

@dsota @blizzardpotato @TTKAegis

**Comment by DynamicSTOP** [comment] 2017-07-05 11:55
@mikenzb  @dsota @blizzardpotato @TTKAegis
I am joining the party. Updated yesterday. So far it was only flashing with white for me.
Ubuntu 14.04LTS. 
![image](https://user-images.githubusercontent.com/9434504/27863067-14af158c-6191-11e7-9f5a-00f7274e1012.png) 
Hardware acceleration inside chrome settings caused my client to freeze after like 1 min or so.

Right now i am trying to play with this one **disabled**
![image](https://forums.adobe.com/servlet/JiveServlet/showImage/2-3863047-79493/8-15-2011+11-50-03+AM.png) 
instructuions: https://forums.adobe.com/thread/891337
So far looks ok, though further investigation required.

**Comment by dsota** [comment] 2017-07-07 02:14
I just wanted to comment that I haven't noticed this issue showing up again ever since I set Slimming paint invalidation to Disabled

**Comment by ethrundr** [comment] 2017-07-07 04:28
@DynamicSTOP @TTKAegis @blizzardpotato 
How's thing on your side?
If no one has further issues so far, I think we can safely close this issue.

**Comment by DynamicSTOP** [comment] 2017-07-07 06:24
@ethrundr 
Disabling flash acceleration greatly reduced number of white squares for me but not removed them completely. I am trying **Slimming Paint Invalidation** right now. It's been just one day since i used it, so i can't say much about is it solved for me or not.

 Anyway let's close it and if anyone else will popup with same problem we can just reopen this issue.

**Comment by ethrundr** [comment] 2017-07-07 07:45
Then, this issue will be closed for now, until further problems detected.

**Closed by ethrundr** 2017-07-07 07:45 UTC
Labels: type:help
