### ISSUE TITLE
add a button/trigger to stop logging battle data

### ISSUE THREAD

**Issue by ztjal** [KC3Kai/KC3Kai#2207] opened 2017-09-03 14:57 UTC
for example, map 1-1, battle data is just junk data, meaningless.
1, add a buttom call "clean", let the people can click to clear battle data for current selected map.
2, add a checkbox call "log", let the people can choose whether to log battle data for current selected map.

**Comment by HitomaruKonpaku** [comment] 2017-09-03 15:09
I asked for it already #2167 but... nvm

**Comment by ztjal** [comment] 2017-09-03 16:31
ok, maybe add a checkbox to stop log battle data is fast and efficient.

**Comment by ethrundr** [comment] 2017-09-09 02:51
Renaming the issue to match the one requested by @ztjal, since the original title is indeed duplicate of #2167.

Just to avoid misinterpreting the suggestion.

**Closed** 2017-09-13 02:31 UTC
Labels: type:enhancement
