### ISSUE TITLE
[Suggestion] Expedition Checker Default

### ISSUE THREAD

**Issue by JD-Kurotoshigami** [KC3Kai/KC3Kai#994] opened 2015-10-30 13:52 UTC
sometimes it is a bit confusing if the exped shown in the checker is not the one you intend to send the fleet to, and could also lead to sending the wrong fleet. I suggest to make a default state of it in which it says [Select an Expedition], [No Expedition Selected] or anything of the kind

**Comment by Javran** [comment] 2015-10-30 14:34
by default whatever change you made persists and is tied to fleets.
I assume when an expedition is returned, people usually just resupply & resend to the same expedition, so what about: when a fleet is returned, setting its expedition to the one fleet just returned from?

**Comment by Javran** [comment] 2015-11-01 03:34
@JD-Kurotoshigami now when fleet returns, in expedition tab, fleet will associate with expedition number it just returned from. It differs from what you want to solve, but at least when you choose not to use expedition tab, it will still sync with our in-game choice. what do you think?

**Comment by ethrundr** [comment] 2015-11-02 01:11
also @Javran, could you lock the "Great" or "Normal" to what the fleet got previously as well or to what the user has set before?
or it is already like that?

**Comment by Javran** [comment] 2015-11-02 03:30
@ethrundr yesterday I pushed another patch to the repo, now great success flag is associated with expedition number, that means expedition tab remembers your great success flag for every expedition, no matter which fleet you are focusing on.
From what I know some great success conditions are still unconfirmed and personally I don't want to put something I'm not sure about .. but you can toggle that button and the expedtiion tab remembers it - you can set it once for all.

**Comment by Javran** [comment] 2017-02-09 06:15
closing because all has been solved: exped tab remembers fleet-expedition pairs, each expedition is bound with its own configs and great success is somehow taken care of by the overdrumming condition checker.

**Closed by Javran** 2017-02-09 06:15 UTC
Labels: type:enhancement
