### ISSUE TITLE
Black screen when using KC3 on iFrame

### ISSUE THREAD

**Issue by whj0000** [KC3Kai/KC3Kai#1531] opened 2016-09-10 10:19 UTC
Hi,
Recently, after switching to another computer, I have encountered the problem of not being able to play via Frame as the entire window is blacked out. There is no problem however when accessing via DMM website and API link. The game still works, even when the window is black the buttons are where they are supposed to be and can be clicked. Here are the screenshots:
No problem yet at this screen:
![1](https://cloud.githubusercontent.com/assets/6337233/18409686/316c2b8e-7780-11e6-88a9-daf13abc6bfa.png)
Problem starts when the game is started, and remains as such. There is still audio however.
![2](https://cloud.githubusercontent.com/assets/6337233/18409687/35230298-7780-11e6-84ff-adb85b89272d.png)

Chrome version: Version 55.0.2853.0 dev
OS: Windows 10 Home 64 bit
KC3 Kai Version: : 30.9.1

I have tried other, older versions but the problem persists. Any help would be greatly appreciated.

**Comment by PurpleCox** [comment] 2016-09-10 21:12
I have the same issue, I just used the site instead, clearing cache does not help.

**Comment by dragonjet** [comment] 2016-09-10 22:55
lastest stable chrome is version 53 only.
54 is beta channel and 55 is dev, canary, canary_asan

there might be a problem starting chrome 54, but we can not be sure if this will persist to the official release of chrome. marking as wontfix until we experience it in chrome stable channel

**Closed** 2016-09-10 22:56 UTC
Labels: wontfix

**Comment by PurpleCox** [comment] 2016-09-10 23:09
Switching back to chrome 53 then to chrome 54 again seems to have fixed the issue, even after replacing all my user data with the backup from when the issue was occurring. So it may just have been a strange one time issue caused by one of the beta/dev updates.
