### ISSUE TITLE
tab was closed without confirmation when new version update

### ISSUE THREAD

**Issue by yeshasuicide** [KC3Kai/KC3Kai#1747] opened 2017-01-19 02:57 UTC
sortie in frame mode
exit confirmation is selected
chrome version:55.0.2883.87
Kc3 version from 30.15.0 to 30.15.1

**Comment by Beregondz** [comment] 2017-01-19 03:24
Happens to me as well since new update alert was added (the message in a new chrome tab warning that some features may not work correctly until the app is closed and updated), both on Iframe and  API.
Very annoying because it might close game in even during sortie/battle

**Comment by sinsinpub** [comment] 2017-01-19 04:03
just go and star it: https://bugs.chromium.org/p/chromium/issues/detail?id=682478

**Comment by ItsCelerity** [comment] 2017-01-19 04:12
This has been happening to me for as long as I can remember. Just made an account to report about it. I starred the issue as well.

**Comment by dragonjet** [comment] 2017-01-19 09:19
duplicate of #1675

**Closed** 2017-01-23 22:34 UTC
Labels: type:duplicate
