### ISSUE TITLE
[Issues] Panel don't start

### ISSUE THREAD

**Issue by nicolas22g** [KC3Kai/KC3Kai#1643] opened 2016-12-02 17:19 UTC
I have issues with API Link.
The game start normally but the panel is stuck at "Waiting for games actions" even if I start a battle or returning to main game menu.

I already try to restart Chrome and to delete the cache. Still stuck

My Chrome version - 55.0.2883.75
My KC3 Kai version - 30.11.3

### Screenshots:
http://puu.sh/sBRPq/3b118a3d72.png

**Comment by Green-Cat** [comment] 2016-12-02 17:33
It's a chrome issue. Duplicate of #1641

**Comment by dragonjet** [comment] 2016-12-03 19:08
for this, we will be adding a "Special DMM Mode" as a new gameplay options. This customizes the DMM website directly, not enclosed in any iframe: #1645

**Closed by dragonjet** 2016-12-03 19:08 UTC
Labels: wontfix
