### ISSUE TITLE
wrong visualization

### ISSUE THREAD

**Issue by simmasa** [KC3Kai/KC3Kai#1611] opened 2016-11-19 09:59 UTC
after the update today the girls bar started to display info in wrong positions and the buttons on the right(music, fit, screen) were all misplaced...after some restart they got in posistion but some bars still has some issues
![bandicam 2016-11-19 19-10-56-545](https://cloud.githubusercontent.com/assets/13229065/20454705/f5f54750-ae8b-11e6-83ff-36aec16123ae.jpg)

Chrome version 54.0.2840.99
Win7 64
KC3 30.11.1

**Comment by dragonjet** [comment] 2016-11-19 18:30
hmmm this is similar to #1592 though I am unable to reproduce.
I tried zooming but doesnt break like that.

**Comment by dragonjet** [comment] 2016-11-19 18:31
closing this, and we can continue for updates on #1592

**Closed by dragonjet** 2016-11-19 18:31 UTC
