### ISSUE TITLE
No data display on the DevTool

### ISSUE THREAD

**Issue by SkyHighll** [KC3Kai/KC3Kai#1203] opened 2016-03-19 13:40 UTC
![20160319_214722](https://cloud.githubusercontent.com/assets/17948903/13898944/f42f14bc-ee1c-11e5-9fba-568a05f649c9.jpg)

**Comment by dragonjet** [comment] 2016-03-19 13:46
hello, can you give us more info

**Comment by dragonjet** [comment] 2016-03-19 14:03
marking duplicate of #1202

**Closed by dragonjet** 2016-03-19 14:03 UTC
Labels: duplicate
