### ISSUE TITLE
Formatting issue of elements on 30.12.0

### ISSUE THREAD

**Issue by MegaAbsol** [KC3Kai/KC3Kai#1647] opened 2016-12-03 14:00 UTC
After updating to the new 30.12.0 version, the positioning of various elements in the DevTools panel is slightly off. The experience bars are higher up, and the icons on buttons have been shifted slightly. The health/ammo/fuel/HQ exp bars are also not completely aligned with the gray background behind them.

Edit: There are also formatting bugs with the combat screen. Looks like some images aren't loading.
Edit 2: This issue also occurs on the expedition screen, and it is impossible to change the expedition number because the hovertext is below the mouse.

### Versions:
Chrome Version: 54.0.2840.99
OS Version: Windows 10, 64-bit
KC3 Kai version: 30.12.0
It used to work fine on 30.11.x.
My screen resolution is 1366x768.

### Steps to reproduce:

1. Open "Play via DMM on frame" (I was also able to recreate this issue on my machine with playing directly on the website and via API link.) 
2. Hit F12 -> KanColle
3. Run the game

### Actual behaviour:
![actual](https://snag.gy/H2QK8v.jpg)
![combat](https://snag.gy/e7jAuH.jpg)
![expedition](https://cloud.githubusercontent.com/assets/10118751/20860083/f2184c9c-b93d-11e6-8618-43ed53b90522.png)
(Due to the gap between the two boxes, when I move my mouse down the hovertext disappears.)

### Expected behaviour:
![expected](https://snag.gy/tRiH0s.jpg)

It seems that the panel itself has become wider as well, although that may be intentional. However, this also caused either the game window or the admiral dashboard to not fit fully onscreen (depending on how large I made the DevTools panel), while previously both of them fit onscreen fine.

**Comment by MegaAbsol** [comment] 2016-12-03 14:43
Furthermore, the Strategy Room CSS also seems to be broken. The sidebar and information are not aligned:
![now](https://cloud.githubusercontent.com/assets/10118751/20860029/cd05ef28-b93c-11e6-941d-379488d5c5f8.png)
![it looks like this](https://cloud.githubusercontent.com/assets/10118751/20860026/bbe8ce9a-b93c-11e6-93aa-7f5952b079cb.png)

I haven't looked through the code, but it might be that some CSS file is missing or not loading correctly?

**Comment by MegaAbsol** [comment] 2016-12-03 15:39
Ok, I just thought to check console, and it does seem like some CSS is not being loaded:
![image](https://cloud.githubusercontent.com/assets/10118751/20860384/c0e514dc-b944-11e6-8166-cde01893b299.png)

**Comment by dragonjet** [comment] 2016-12-03 19:01
thanks for the report, though this is a duplicate of #1592. updates will be continued on that thread. thanks.

**Closed by dragonjet** 2016-12-03 19:01 UTC
