### ISSUE TITLE
Saury Fishing quest still active in active quest logs

### ISSUE THREAD

**Issue by Acornzstudio** [KC3Kai/KC3Kai#1001] opened 2015-11-01 19:03 UTC
It's the saury quest where you need to collect 30 sauries.

**Comment by dragonjet** [comment] 2015-11-02 00:16
You can manually override the quests from the Strategy room > Flowchart.
Each quest has a remove button, and for tracked ones, have add/subtract buttons
This is usually the case if using multiple devices or viewers where the cache are separate.

Marking duplicate of #933

**Closed** 2015-11-02 03:17 UTC
Labels: duplicate
