### ISSUE TITLE
Not loading, white screen on 'Play via API link'

### ISSUE THREAD

**Issue by prokia123** [KC3Kai/KC3Kai#1565] opened 2016-10-28 05:46 UTC
Playing via API link suddenly stopped loading for me, got nothing but a white screen. Playing on DMM Website and Playing on Frame worked fine though.

**Comment by ethrundr** [comment] 2016-10-28 05:49
duplicate of #1549 
I'm closing this issue, please refer to said issue for fix.

**Closed by ethrundr** 2016-10-28 05:49 UTC
