### ISSUE TITLE
Quest translation is not along to new version for saperate categories

### ISSUE THREAD

**Issue by tinefanforvettel** [KC3Kai/KC3Kai#2974] opened 2020-04-04 04:37 UTC
Chrome versions 80.0.3987.163
Windows 10 OS Version 1909 (Build 18363.720) 64bit single language
JavaScript | V8 8.0.426.30
KC kai 34.4.4 why can't update to 34.4.5?
Build: webstore
Game Mode: "Customize DMM Website" (the default)

I'm out of method to resovle 
![2020-04-04 11-25-43 14](https://user-images.githubusercontent.com/20445117/78418640-3967c600-7668-11ea-8168-ce1ec530b686.jpg)
![2020-04-04 11-33-33 23](https://user-images.githubusercontent.com/20445117/78418642-3cfb4d00-7668-11ea-953a-1d83558c0bf9.jpg)

[[20232592] ErrorLog 2020-04-04.zip](https://github.com/KC3Kai/KC3Kai/files/4430744/20232592.ErrorLog.2020-04-04.zip)

**Comment by tinefanforvettel** [comment] 2020-04-04 04:40
Sorry for the same problem

**Comment by planetarian** [comment] 2020-04-04 04:45
duplicate of: #2966

**Closed** 2020-04-04 04:50 UTC
Labels: type:duplicate
