### ISSUE TITLE
Uncaught TypeError: Cannot read property 'api_fdam' of undefined

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/KC3Kai#770] opened 2015-09-07 08:29 UTC
Just update the game, the KC3kai, and try PvP

This what I got:
![screen shot 2015-09-07 at 17 27 53](https://cloud.githubusercontent.com/assets/13522800/9712491/e9269340-5585-11e5-916d-39002ee6f228.png)

Prediction for PvP is not loaded, at all.

**Comment by Javran** [comment] 2015-09-07 08:37
Same thing here, the battle prediction doesn't show up.
But if I feed the network packet manually to my lib, it works.

(btw where can I find the error message?)

**Comment by dragonjet** [comment] 2015-09-07 09:07
duplicate of #769

**Closed by dragonjet** 2015-09-07 09:07 UTC

**Comment by ethrundr** [comment] 2015-09-07 09:44
@Javran the error message on my right-bottom side?
I press F12 while on the KC3kai panel. It'll show up another developer panel, that monitors the state of the KC3kai.... :smile:

**Comment by Javran** [comment] 2015-09-07 10:05
@ethrundr that doesn't work here.. I tried focusing on web page & dev page and pressing F12, all results in the devpage being disappearred...

**Comment by dragonjet** [comment] 2015-09-07 10:52
ah what I do is, separate the devtools into a new window, then ctrl+shift+J on that window, then just redock it back to the main browser

**Comment by Javran** [comment] 2015-09-07 11:01
ah that does work for me. I've been debugging using `alert` all the time because I can't find where does `console.log` output to ...

**Comment by dragonjet** [comment] 2015-09-07 11:02
:+1:
