### ISSUE TITLE
Icon, Text misalignment

### ISSUE THREAD

**Issue by lagrinne** [KC3Kai/KC3Kai#1865] opened 2017-03-01 01:20 UTC
### Versions:
Google Chrome	56.0.2924.87 (Official Build) (64-bit)
Windows 10 Education 64-bit
KanColle Command Center 改 31.1.1

### Steps to reproduce:
Updated from previous released version 31.1.0
Monitor resolution : 1366 x 768

### Actual behaviour:
Misaligned text and icons on almost every page. No misalignment only on KC3改 settings page and in-game subtitles. Issue only appeared for me in this version. Issue persists even after trying to resize the panel and game windows. Tried to see if the issue persists on other extensions, websites but I did not observe similar problems.

### Expected behaviour:
Aligned Text and icons

### Screenshots:
http://i.imgur.com/dnsyJt3.png
http://i.imgur.com/cEOKdBW.png
http://i.imgur.com/gv5NMds.png

**Comment by dragonjet** [comment] 2017-03-01 06:50
this is a known bug, see #1592

the cause is a bad extension installation on the side of chrome, no problem on your side nor on ours. chrome forgets to copy our "bootstrap" style sheet. some have even tried copying the missing file manually but chrome says no and gets corrupted.

common solutions:
* reinstall but will clear your strategy room
* wait for next update as chrome will re-copy the files

**Comment by dragonjet** [comment] 2017-03-01 06:50
closing as duplicate

**Closed by dragonjet** 2017-03-01 06:50 UTC
Labels: type:duplicate
