### ISSUE TITLE
API error while disassembling ships in the fleet

### ISSUE THREAD

**Issue by october10th** [KC3Kai/KC3Kai#2331] opened 2017-11-18 17:15 UTC
### Versions:
- Your Chrome version 62.0.3202.94
- Your OS and its version Mac OS X 10.11.6
-bit or 64bit? 64
- Your KC3 Kai version webstore version 31.11.1

### Steps to reproduce:
disassemble ships in the fleet will get this error

### Actual behaviour:
as shown in the screenshots

### Screenshots (if applicable):
Before:
![2017-11-18 12 03 41](https://user-images.githubusercontent.com/4963914/32982867-28fdfafc-cc59-11e7-9561-545313b3243c.png)
After disassembling Yuudachi:
![2017-11-18 12 04 02](https://user-images.githubusercontent.com/4963914/32982869-2f0b9382-cc59-11e7-9c4f-032af02221cd.png)
### Error Report (if applicable):
[KC3-Error-1511024632.txt](https://github.com/KC3Kai/KC3Kai/files/1484824/KC3-Error-1511024632.txt)

**Comment by mikenzb** [comment] 2017-11-18 21:57
Has been reported, this is a duplicate of #2327 

Will be fixed in the next release.

**Closed by mikenzb** 2017-11-18 21:57 UTC
Labels: type:duplicate
