### ISSUE TITLE
Name in kanji in Ship Library, names of stats, bug with the "image-switching-disaster" notice

### ISSUE THREAD

**Issue by Syntax7error** [KC3Kai/KC3Kai#1504] opened 2016-08-22 11:03 UTC
Hello

I am using the latest version of KC3 (30.8.1) on Comodo Dragon browser (a Chromium clone), in Windows 7.

I see two things that can be improved in the _Ship Library_ ot the _Strategy Room_:
- the name of the ship-girl in Japanese is written in hiragana, that is useless because the in-game names are mostly written in kanji. When one is looking for a particular ship in his fleet, it is impossible to do it using names in hiragana.
- there is a problem with the "image-switching-disaster" notice: if one clicks on it, it disapears and it is not possible to copy the link to paste it in the Flash player options, or even to reach Adobe's Global Security Settings panel page. The only other way is to open the _Help topics_ menu, but it is not evident for everyone that the solution to the "image-switching-disaster" is in this menu.

![ship library](https://cloud.githubusercontent.com/assets/21103170/17852216/ff57d94c-68a0-11e6-9d45-a8b0a8f5cce7.png)

Thanks.

**Comment by dragonjet** [comment] 2016-08-22 11:44
1. that is intended as that is the api-yomi, and may not be something we need perfected other than JP language setting. Following is how it looks in JP, and is the intended behavior, kanji and the reading characters side by side

![ss 2016-08-22 at 08 39 27](https://cloud.githubusercontent.com/assets/557312/17853629/b7c46a7a-68a8-11e6-9872-10a9efe370a5.jpg)

2. agreed, let's update that one to not hide until next refresh

**Comment by Syntax7error** [comment] 2016-08-22 11:55
@dragonjet: I made a mess with threads while editing, and I couldn't put another issue with the Ship List:
- some of the names of the stats are not in English (eg. souk for armour, soku for speed, etc.) It may be Malaysian or Tagalog maybe?

**Comment by dragonjet** [comment] 2016-08-22 11:57
those are the API names of the stats :sweat_smile:

**Comment by Syntax7error** [comment] 2016-08-22 12:06
Oh, okay. I do not know much about these API things...
It didn't look much like Malaysian or Tagalog, but not much to Japanese also. :blush:

**Comment by sinsinpub** [comment] 2016-08-22 13:09
for 2), just copy it from Help Topics on right top...

**Comment by Syntax7error** [comment] 2016-08-22 13:32
@sinsinpub 

> for 2), just copy it from Help Topics on right top... it's always there :sweat:

I am just saying that it is not evident for people not accustomed with KC3Kai, furthermore if they do not understand English good.
I quicklyu found the way to get the link and solve the problem, but I am reporting this thing because I think that everyone may not be in that case, and I know that on the Internet, most of things have to be idiot-proof...

**Comment by sinsinpub** [comment] 2016-08-22 13:53
@Syntax7error it's nice to report the inconvenience behavior for copying the link. a quick improve has been committed at 462127a. however if someone not good at English, there's no way to help :joy:

**Comment by dragonjet** [comment] 2016-08-23 12:54
agreed with @sinsinpub's pushed fix, we can probably close this now?

**Comment by Syntax7error** [comment] 2016-08-23 12:58
@dragonjet: no problem with me.

**Closed** 2016-08-23 13:27 UTC
Labels: type:enhancement
