### ISSUE TITLE
Kai Ni Badge Generator

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/KC3Kai#1028] opened 2015-11-15 14:24 UTC
Integration with http://threebards.com/kaini/

Will auto-fill the kai ni badger using your KC3 data

**Comment by nagatoyk** [comment] 2015-11-15 15:23
这是要做啥???

**Comment by Javran** [comment] 2015-11-15 15:37
@nagatoyk hm, I guess you'd better speak in english xD
For now you have to fill in everything manually to http://threebards.com/kaini/
I think @dragonjet wants to make something simillar to this. but having player's ship list available,
we can fill in information automatically.

**Comment by bcc32** [comment] 2015-11-15 17:26
Are you planning to implement as part of KC3Kai or to submit data to threebards?

**Comment by dragonjet** [comment] 2015-11-15 22:54
yep @Javran was right, that the link is currently manual and @bcc32 we could have our own, coz I don't think they accept data atm

**Comment by Javran** [comment] 2015-11-22 02:13
just wondering if anyone here happens to know the author of http://threebards.com/kaini/ ?
its bug report link looks invalid (page not found)
maybe we can negotiate to make things export/import-able.

**Comment by dragonjet** [comment] 2015-11-22 03:24
maybe someone from himeuta knows ( ͡° ͜ʖ ͡°)

**Comment by McDohl** [comment] 2015-11-23 15:21
@Javran http://www.himeuta.net/f39-kancolle-modules/tool-kancolle-kai-ni-badge-generator-2145.html
this is the creator

**Comment by cyrismustang** [comment] 2016-01-02 23:11
Ello, Ryuuhou Kagiyama here.  Are you guys looking to collab for the badge generator?  Currently all the info is stored in the browser's session storage, so theoretically I can make an API that will do the exact same thing.  This will also allow users to permenantly save and load from any location.

**Comment by Javran** [comment] 2016-01-03 04:35
@cyrismustang ah thanks for the help, we have not yet come up with a detailed plan, but I'd like to work on this.

For now I can find these keys in localStorage:

![2016-01-02_232413_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/12077237/00b4189c-b1a8-11e5-81fe-4470566f016b.png)

looks like most values are base64 encoded JSON data. can you give more details about what's stored locally and how they are represented? Also I took a closer look at `colle` and `k2`, and found things like `"tenryuu1":true,"tatsuta1":true,"kuma1":true,"tama1":true` and `"fubuki2":false,"murakumo3":false,"ayanami2":false,"mutsuki3":false` what do those numbers after ship names mean?

**Comment by bcc32** [comment] 2016-01-03 04:51
@Javran probably remodels, i.e., 'mutsuki3' => Mutsuki Kai Ni, etc.?

**Comment by Javran** [comment] 2016-01-03 05:02
@bcc32 could be but I can't get why it's 3 for mutsuki and 2 for ayanami..

**Comment by cyrismustang** [comment] 2016-01-03 05:44
There is another JSON file called db.json where the IDs are stored.  Girls are identified by CG chronologically so mutsuki2 is valentines Mutsuki before her kai 2 came out.

http://threebards.com/kaini/db.json

**Comment by Javran** [comment] 2016-02-06 17:58
@cyrismustang sorry I've missed you response. and thanks for the info, I'll take a look and see what I can do.

**Comment by Javran** [comment] 2016-02-06 18:47
@cyrismustang I guess we can fill in following parts: `ttkName`,`ttkName`,`ttkServer`, `fleet`, `fleetLvl`, `colle`, `k2`. I'll try to encode them in the same ways as stored in localStorage.

For exporting data, I can think of 2 ways:

* a JSON data like `{"fleet": "foo", "k2":"bar"}` for users to copy and paste
* pass them as querystrings e.g. `http://threebards.com/kaini/index.html?fleet=foo&k2=bar`

what do you think?

**Comment by cyrismustang** [comment] 2016-02-07 05:36
Is it possible to send as a post request with the JSON data as the body?  I
worry there is a chracter limit for get URLs

**Comment by Javran** [comment] 2016-02-07 06:04
@cyrismustang I guess I can do that, not sure if @dragonjet has better solutions?

**Comment by Javran** [comment] 2016-02-07 08:24
I'd like to share these 2 tables for converting between badge id and master id (from api_start2):
 
https://gist.github.com/Javran/8774fa38f8b3f5f9e39a

I feel exporting fleets needs more work (will need a complete mapping between badge id <-> master id, which I find it hard to automate), so let's first get `k2` and `colle` to work.

**Comment by cyrismustang** [comment] 2016-02-07 08:48
Thanks for the tables, I am currently in Japan atm so I don't have access to my source code until 2/18 (but I can still update new ships and k2).  Luckily there won't be any new ships for a while after the event, so I will have time to write the API.

For exporting, I can keep track of your conversion table on my side so you can just send the master IDs.  Since the badge generator is not automated either, it will require me to make an update before new ships and K2 are added anyways.

**Comment by dragonjet** [comment] 2016-02-07 10:34
I agree with doing `post` rather than `get`, the only reason we're not able to do it on our replay feature is that the replay script is also client side. since the k2 poster can do server-side, we should do it

thanks for the updates all good job so far in the process with integration :+1:

**Comment by Javran** [comment] 2016-02-08 06:01
Almost done, checkout [dev-badge-support](https://github.com/KC3Kai/KC3Kai/tree/dev-badge-support) and have a try!

![2016-02-08_001952_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/12879108/9943fcb0-cdfc-11e5-8dc2-38926864b03b.png)

These fields are supported: `colle`, `k2`, `ttkLvl`, `ttkName`, `ttkServer`, `fleet`, `fleetLvl`

I'm terrible at writing UI, so someone please make this look better:

![2016-02-08_004325_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/12879161/247787b6-cdfd-11e5-8110-2975af185624.png)

In the Strategy Room you'll see this new tab "Badge", there are 2 exporting methods:

* From Current Ship List: you don't need to do anything, just click "Export"
* From In-Game Picture Book

you need to go to your in-game picture book:

![2016-02-08_004613_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/12879183/85ee8abc-cdfd-11e5-9354-f41d63cb609c.png)

click these 5 tabs, don't have to wait for the pictures to load, and you'll see:

![2016-02-08_004815_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/12879195/b1795e14-cdfd-11e5-8cde-38813708c917.png)

After all 5 volumes are sync-ed. click "Export".

You'll see some key-value pairs, go to Kaini Badge Generator and open localStorage editor then paste these values in. click "Load", done.

In future last step will become a POST request.

@cyrismustang I upgraded these id tables, now it's [K2Badge.js](https://github.com/KC3Kai/KC3Kai/blob/dev-badge-support/src/library/modules/K2Badge.js), it contains all mapping between KBG ids and master ids, self-documented and almost standalone (only requires jquery) in case other KC helpers want to do something similar.

**Comment by Javran** [comment] 2016-02-19 04:58
@cyrismustang how is it going? let us know if you need any help about the integration. you suggested about keeping conversion table on your side and that will be great help because master ids are more commonly used in KC3 and hopefully many other KC helpers.
My suggestion of the protocol will be like:
* our client will prepare information that does not require conversion (`ttkName`, `ttkLvl`, `ttkServer`, `fleetLvl`), a list of ship master ids and fleet infomation (with fleet id replaced with master id)

* on your side you can convert master ids into your badge ids, then maybe ask users to choose which part of the data should be imported.

Most of the implementation is done, just need to more them to your side, id conversion can be found in https://github.com/KC3Kai/KC3Kai/blob/dev-badge-support/src/library/modules/K2Badge.js and we also have https://github.com/KC3Kai/KC3Kai/blob/dev-badge-support/src/library/modules/RemodelDb.js to calculate relationships between remodels (so to figure out "original ship" or final forms of a ship, etc.) Feel free to ask questsions xD

**Comment by cyrismustang** [comment] 2016-02-19 10:44
@Javran Hey!  I just came back from Japan today.  I can finally start work on this, so I will have the badge generation by the end of the weekend.  Here's what I will do:

- Accept POST request with json object with information
- Maintain the conversion table so you can just send master ID in the k2/colle objects
- I will probably redirect the user to the main Kai 2 page, since I will be accepting all their data.

I can work on a version with server-side Canvas Rendering later, if you want to send me the type of data and want just the image data back.

**Comment by Javran** [comment] 2016-02-19 17:30
@cyrismustang good to hear that! since you'll accept all the data, would you make some fields optional? We can gather all info needed and ask user to choose which part to be exported. and then, we can send POST request or use incoming server side rendering feature xD.

btw does your badge generator have any open source repo online? it's totally fine if you don't want to make it open though.

**Comment by cyrismustang** [comment] 2016-02-19 19:05
@Javran Yes, technically all fields are currently optional.  The main page is what happens when no fields are supplied (Nameless Admiral, Unknown Server, etc.)

I don't have it open sourced or anything atm.  Not because it's secret, but because it is literally 1 JS file compressed with jscompress.com.  I can send you the uncompressed file if you want it.

**Comment by Javran** [comment] 2016-02-20 03:51
@cyrismustang I see, maybe on our side we only need to construct the request by asking user about what to export, and fill in blanks as necessary.

for me I want the source code just to see how it works, there are some complication regarding the conversion table. mostly about figuring out ship remodels and some preprocessing stuff (when new ship / remodel is out). It'll be easier for me to figure out how to move conversion table to your side if I can have access to the code and experiment what works out the best.

for open sourcing your code, I think it's totally fine even if you just have one file. sites like github have made great supports for people to make contribution or track bugs. but it's all up to you, I'm good with either way of sharing code xD

**Comment by cyrismustang** [comment] 2016-02-20 15:20
@Javran do you happen to keep track of master ID to ship classification?  If so, perhaps it is better for KC3 to send the ships prestructured.  Something like what you're doing in [showcase.js](https://github.com/KC3Kai/KC3Kai/blob/90a415e4a1225ba61e78be42efd3f039a11c5746/src/pages/strategy/tabs/showcase/showcase.js), except to consolidate BB+BBV, CL+CLT, and SS+SSV.  So the expected request will be:

`
k2: {
  ...
  "cv": [array of master ids],
  ...
}
`

This way, I don't have to maintain an additional table for classification, since I don't have access to the ship's api_stype.

Here's the gist of my megafile: https://gist.github.com/cyrismustang/f48e8c43e8c4f93460f0

**Comment by Javran** [comment] 2016-02-20 17:08
@cyrismustang I'm thinking about something a bit different, what about sending you a list of ship ids and construct `k2` and `colle` on your side. the request would look like (all fields are optional):
```
{ fleet: [[{id: 318, lvl 122},null,null,null,null,null], ... ]
, ships: [1,2,6,7.....]
, k2Flag: true
, colleFlag: true
, ttkLvl: 100
, ttkName: foo
, ttkServer: 5
}
```

When both `k2Flag` and `ships` are present and `k2Flag` set to true, we import kai2 info,
something similar for `colleFlag` and `ships`.

Because I've already implemented code for generating whole `k2` structure (so yes,I can keep track of ship types xD) and other fields, we can move that part of code to your side to save some work. the tradeoff is you have to update conversion table when new ships or remodels is available, what do you think?

**Comment by cyrismustang** [comment] 2016-02-20 18:53
@Javran Okay, as long as there is a way for my side to get ship types that will be fine.  Currently the conversion work is already done using your tables (I'm totally fine with updating them), I just need to place them into their Ship Type now.

**Comment by Javran** [comment] 2016-02-20 19:17
@cyrismustang  I actually don't actually have any handling for ship types, maybe you can do something similar to this: I keep a temporary array, while converting kai2 ship ids into `k2` ids, I push these ids into this array (let's call it `shipIds`).
Since your `k2` is already well-structured, I use it as a template and traverse it to build a new one, with values replaced by `shipIds.indexOf(id) !== -1`. see: https://github.com/KC3Kai/KC3Kai/blob/dev-badge-support/src/pages/strategy/tabs/badge/badge.js#L113-L134

**Comment by cyrismustang** [comment] 2016-02-20 19:56
@Javran Unfortunately K2's structure technically is not defined and can't be relied upon since it is generated from the DOM.  What I can do instead is I can use jQuery to find the ship's element in the DOM and extract the ship class.  That way we don't have to send ship classes.  Not the prettiest solution.

**Comment by Javran** [comment] 2016-02-20 20:49
@cyrismustang ok I see, let's then go back to the format you proposed:

```
{ fleet: [[{id: 318, lvl 122},null,null,null,null,null], ... ]
, k2: { ... "cv": [array of master ids], ... }
, colle: ...
, ttkLvl: 100
, ttkName: foo
, ttkServer: 5
}
```

btw are you good with packing `fleet` and `fleetLvl` together like above?

**Comment by cyrismustang** [comment] 2016-02-21 00:46
@Javran Yes, packing fleet and fleet level would be fine.  I'll have something pretty soon to send a POST to.

**Comment by cyrismustang** [comment] 2016-02-21 07:53
@Javran Okay, I have something listening for post requests at http://threebards.com/kaini/api.php.  If you post the object to this address, it will give you a reduced webpage with only the generated badge.

POST form structure (please JSON.stringify the values):
`
 {
  fleet: '[[{id: 318, "lvl":22},null,null,null,null,null], ... ],  //4 arrays of 6 ships
  k2: { ... "cv": [array of master ids], ... }
  colle: '[array of all owned ships]',
  ttkLvl: 100,
  ttkName: 'foo',
  ttkServer: 5
 } 
`

**Comment by Javran** [comment] 2016-02-21 16:14
@cyrismustang great! I'll have a try.

**Comment by Javran** [comment] 2016-02-21 17:46
@cyrismustang I tried posting some data, there is a message reads `Number of elements in POST data: 6` on top, but the badge is not rendered, could you check if the format is correct (excerpted from resulting page):

https://gist.github.com/Javran/7dde5120eb82f05befbd

**Comment by cyrismustang** [comment] 2016-02-21 18:15
@Javran Hmm, if you try to click on Badge/Poster/Furniture, does it render?  Your data works for me if I send it as an HTML form.

Your data: http://threebards.com/kaini/test.html

**Comment by Javran** [comment] 2016-02-21 18:34
@cyrismustang ops my fault, it works incognito mode, after clearing localStorage now it works.

Fleet tab is not quite working though: it was correct first time switching to fleet tab, then after switching to other fleets, all icons become "undefined".

**Comment by cyrismustang** [comment] 2016-02-21 21:38
@Javran The fleet thing was a bug on my part.  It should be fixed now.  Can you confirm?

**Comment by Javran** [comment] 2016-02-21 22:12
@cyrismustang yes, I can confirm, everything starts to work, cheers!
would you mind continue working on few more improvements on this?
I'm stilling thinking about how passing only one list of ship Ids and figure out `k2` and `colle` data on your side.

while I still need to understand difficulty with `k2`, `colle` part is easy, here is another table:

https://gist.github.com/Javran/2a8439bf984025d15592

what it does is to convert ship master id to origin master ship id (e.g. mutsuki kai 2's id to mutsuki's id), when you see the list of ships, you can pass every master id through this table, and get a list of origin master ids(might need to remove duplicates), then you can proceed with this result to do what you used to do on parsed `importColle`.

This table also needs to be updated every time something new comes, but it's generated from master data.

**Comment by cyrismustang** [comment] 2016-02-22 02:21
@Javran I can attempt this if I use jQuery on my side to figure out ship type.  For your request, don't send K2, just send colle.  I'll see what I can do to figure out the implied k2 ships.

**Comment by Javran** [comment] 2016-02-22 03:10
@cyrismustang does http://threebards.com/kaini/db.json provide any help on this, I find ship type is there.

an off-topic question: where can find secretary ship pictures rendered in the badge? looking at the page source I know there is things like `icons/isonami1.png`, what is the path to isonami1 if she is set as secretary ship?

**Comment by cyrismustang** [comment] 2016-02-22 03:18
@Javran Hurp it would.  I guess that makes it easier to generate the K2 on my own now.

There is another directory with the same structure as icons called full.  So isonami1 is in `icons/dd/isonami1.png` and her full image would be `full/dd/isonami1.png`.

**Comment by Javran** [comment] 2016-02-22 03:36
@cyrismustang  good to hear that, then I guess just sending a list of ships should be enough for `k2` and `colle`. can we go back to the format I proposed before: using `ships`, `k2Flag`, `colleFlag` instead of `k2` and `colle`? just in case someone want to import one but not the other, I suspect this rarely happens though.

**Comment by cyrismustang** [comment] 2016-02-22 03:49
@Javran Yeah, you can change it to `ships`.  I also suspect that wanting to only import one type of data is rare, but it's pretty easy to do on this side.

Now that I made a table of ship CG relationships, do you think I should make a version where I limit the user to ONLY be able to select CG from ships they have?  Or would it be futile since they can just make their own badge?

**Comment by Javran** [comment] 2016-02-22 04:07
@cyrismustang thanks! let me know when the change is done. about the limited version I think it's totally up to users, we don't have to limit user of doing anything. besides what if one wants to set an abyssal as secretary xD.

**Comment by cyrismustang** [comment] 2016-02-22 04:16
@Javran Okay, the change should be done.  I also updated the script at http://threebards.com/kaini/test.html for testing kai 2 to colle, but you should send your own current ships.

**Comment by Javran** [comment] 2016-02-22 04:34
not working this time, data: https://gist.github.com/Javran/6dd4f5846a0b8aa65c5e

**Comment by cyrismustang** [comment] 2016-02-22 04:49
@Javran Maybe clear your cache or localstorage again?

What I get: http://i.imgur.com/wpaL7GN.png

**Comment by Javran** [comment] 2016-02-22 05:03
@cyrismustang now it works, but I should have a full collection of DDs but some of them are missing in the result. for example I should have Umikaze Kai (master id 350) but she is not there, maybe you haven't converted ship Ids through "origin table"?

**Comment by cyrismustang** [comment] 2016-02-22 05:20
@Javran You're right, I left out all the ships who have custom CGs.  I just updated the conversion.json and now you should have all 77 destroyers (after clearing your cache).

**Comment by Javran** [comment] 2016-02-22 05:44
@cyrismustang It's working now. I still need to make fields optional but you part is perfectly done, nice work!

I might write something about how to update those tables in case of future maintenance. will tell you about the progress.

**Comment by Javran** [comment] 2016-02-22 06:22
@cyrismustang I just created a repo https://github.com/Javran/badge-supports,
basically these are tools for updating conversion tables.
you can host it (`python -m SimpleHTTPServer` should do) and take a look.
There are 3 links that prints out things useful for 3 conversion tables respectively.
![2016-02-22_011150_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/13210858/4fb9c3d0-d901-11e5-9ec7-e551c5f8e39f.jpg)
I'm terrible at doing UI stuff, feel free to make improvements or live with it (sorry again).

for now I feel updating everything is very complicated, I'll update these tables myself asap after every maintenance, this will be simplified in future.

**Comment by Javran** [comment] 2016-02-22 08:31
![2016-02-22_032846_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/13213095/7203874c-d914-11e5-9575-85f000c8d50d.jpg)

@dragonjet Thanks to @cyrismustang the integration is done, would you mind checking out `dev-badge-support` and make some improvements on UI?

**Comment by Javran** [comment] 2016-02-22 09:03
@cyrismustang I find Nachi in k2 picture but not colle one (Zara & Hatsuzuki are also missing, I remember seeing them before), could you help troubleshotting?

**Comment by cyrismustang** [comment] 2016-02-22 12:42
@Javran Nachi is 6th ship on the CA badge.  Her icon is her normal form.

I added Hatsuzuki and Zara back, looks like the DB was unsynced since I added them while I was travelling in Japan.  That's what I get for not using source control.

**Comment by Javran** [comment] 2016-02-22 16:53
@cyrismustang ok, new ships are back.

about Nachi, I meant her is not selected despite I have her in my ship id list. (zara is also missing)
![2016-02-22_114627_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/13225252/03d9b5de-d95a-11e5-9d92-e5a4b5378d0e.jpg)

**Comment by cyrismustang** [comment] 2016-02-22 19:27
@Javran Strange, Nachi is just completely missing from my relationship table.  I also forgot to add the new ships to that table...  When I get home I'll just go through every ship just to make sure.

**Comment by cyrismustang** [comment] 2016-02-23 01:06
@Javran Okay, Nachi is back.  However, Zara seemed to already be in the list.  Can you send me your list of ships?  With the test data that I have, it doesn't seem like you had Zara.

**Comment by Javran** [comment] 2016-02-23 01:34
@cyrismustang weird, I can now see Zara but not Nachi https://gist.github.com/Javran/98b57968532bd9584392

**Comment by cyrismustang** [comment] 2016-02-23 01:56
@Javran Visit `http://threebards.com/kaini/conversion.json` and try to see if you can find the entry for nachi2 to nachi1 in there?  Maybe needs cache refresh.

**Comment by Javran** [comment] 2016-02-23 02:07
@cyrismustang yeah, I can find the entry. the problem is solved, thanks xD

**Comment by dragonjet** [comment] 2016-02-27 11:32
UI Enhancements added 0619634a3a977896be347a2fe066f1adea2ce3cc on branch `dev-badge-support`
@Javran you can create a pull request

**Comment by cyrismustang** [comment] 2016-02-27 13:19
@Javran Just before you do pull request, can you assign the POST URL to `index.php` instead of `api.php`?  I am going to convert the indexes into the API because they are identical, and this will allow you to get multiple languages by targeting `XX/index.php`.

**Comment by Javran** [comment] 2016-02-27 17:23
@dragonjet thanks for UI enhancement, ready for PR.

@cyrismustang I've implemented that, it now submits to `http://threebards.com/kaini/index{,-jp,-cn}.php` depending on the language.

**Closed** 2016-02-27 22:31 UTC
Labels: feature

**Comment by Javran** [comment] 2016-02-29 09:05
@cyrismustang let me know when satsuki kai ni is available on badge generator. will update files accordingly.

**Comment by Javran** [comment] 2016-02-29 10:30
@cyrismustang assuming you will be using `satsuki2` as satsuki kai ni id, I've made changes accordingly: https://raw.githubusercontent.com/Javran/badge-supports/master/K2Badge.js https://raw.githubusercontent.com/Javran/badge-supports/master/origins.json

**Comment by cyrismustang** [comment] 2016-02-29 12:43
@Javran Thanks, you shouldn't have to do any more on your end now, I handle it all on this side!  Yes, it is `satsuki2`.  It should be ready now, all you have to send is 418 and satsuki should show up.

**Comment by Javran** [comment] 2016-03-01 05:39
@cyrismustang I already updated and tested. thanks again for your work xD

**Comment by Javran** [comment] 2016-03-11 05:16
@cyrismustang hi you might have got asagumo's picture wrong:

this is the screenshot from wiki:
![2016-03-11_001352_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/13693929/4a0024c2-e71e-11e5-99b5-d6e8f801018f.jpg)

seems in your generator `asagumo1` is actually Asagumo Kai and `asagumo2` is Asagumo before remodeling.

**Comment by cyrismustang** [comment] 2016-03-11 05:31
@Javran that seems to be the case, I must have just named the images in the wrong order, the rest of the data should be good now

**Comment by Javran** [comment] 2016-03-11 05:39
@cyrismustang full pictures are now looking good, but http://threebards.com/kaini/icons/DD/asagumo2.png is not yet fixed.

**Comment by cyrismustang** [comment] 2016-03-11 12:52
@Javran likely a cache refresh issue, shows up as a smile for me

**Comment by sinsinpub** [comment] 2016-03-14 16:56
yesterday I exported my fleet including Zara Kai, but shown as Okinami... is there any mismatch?

**Comment by cyrismustang** [comment] 2016-03-14 17:25
@sinsinpub Hmm, can you check these IDs for me?  I may have them mixed up:

Okinami: 358
Zara Kai: 359

**Comment by Javran** [comment] 2016-03-14 17:28
@cyrismustang same thing happens to me, their IDs are the other way around.
![2016-03-14_132648_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/13753252/9765c664-e9e8-11e5-9745-68fee8182b17.jpg)

**Comment by Javran** [comment] 2016-03-14 17:33
@cyrismustang would you mind opening a github repo for your badge generator? If you don't feel comfortable sharing the code, you can leave the repo empty and only use issue tracking feature.

**Comment by cyrismustang** [comment] 2016-03-14 17:36
@Javran Okay, I just need to switch the entries (they were also switched in the K2Badge.js).  Any other issues you can report here: https://github.com/cyrismustang/k2badge

**Comment by Javran** [comment] 2016-03-14 17:46
@cyrismustang thanks for opening the repo, will be a good place for future bugs or discussions. about master ids, that was actually my fault. just fixed it on our side.
