### ISSUE TITLE
KC3Kai Dev not working

### ISSUE THREAD

**Issue by RredderR** [KC3Kai/KC3Kai#909] opened 2015-09-30 03:53 UTC
![bug](https://cloud.githubusercontent.com/assets/14126825/10184051/b9a55f02-6769-11e5-8527-b032d2252d25.png)

KC3Kai doesn't seem to load very well. This happens after a few seconds (approximately 1-3 seconds before this shows up).

**Comment by RredderR** [comment] 2015-09-30 03:54
![bug2](https://cloud.githubusercontent.com/assets/14126825/10184067/e890f146-6769-11e5-918b-4a95174dfabb.png)

Even though I installed it correctly.

**Comment by nekoworkshop** [comment] 2015-09-30 04:40
I'm able to reproduce the problem when my language is set to Thai. Looks like they removed some untranslated files... I've added back the original files.  https://github.com/KC3Kai/kc3-translations/commit/96ed4a681c23289b4d1773e293773aadf038a637

**Comment by RredderR** [comment] 2015-09-30 04:41
So what should I do?

**Comment by nekoworkshop** [comment] 2015-09-30 04:44
You may pull the latest version now, the problem should be fixed. Just to be sure, did you set your language to Thai?

**Closed** 2015-09-30 07:56 UTC
Labels: help
