### ISSUE TITLE
Bd6 incorrect counter

### ISSUE THREAD

**Issue by Javran** [KC3Kai/KC3Kai#1776] opened 2017-02-01 20:56 UTC
![2017-02-01_155528_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/22525840/ef7c0248-e896-11e6-9ce4-31415cf3c31a.jpg) sunk 4 at a time, counted as 5.

Edit: and even worse: there's no way to reset it from devtools, mark it as completed manually and refresh questlist, the state `5/5` will just come back.

**Comment by nonsensed** [comment] 2017-02-01 22:25
I've been keeping quiet about it since I already brought this up when the quest change was a Pull Request, but I was able to cause this to happen as well just now.

![img](http://i.imgur.com/dL0C3BZ.png)

Method: Activate Bd6, do not activate bd5, sink 4 transports, don't look at quest page until 4 transports sunk.

**Comment by Javran** [comment] 2017-02-01 23:58
slightly off-topic, I'm thinking about the behavior of toggling quest states from devtools, especially
when changing a completed one to an in-progress one, should we also set all tracking data to 0?
Because by the time user decide to toggle quest states manually, either user have misclicked, or something has went wrong, perhaps clearing tracking info is fine for both case:

- if user misclicks, auto-adjustment will come into play when next time user visits quest list.
- if something is wrong (like this one), user will still be able to fix it without having to go to the Flowchart tab in SR, again auto-adjustment will also help if tracking data has been reset to 0.


(I'm refering to this part of the code: https://github.com/KC3Kai/KC3Kai/blob/b1c13c2a2b399944c545dddc50f355294fb917ea/src/pages/devtools/themes/natsuiro/natsuiro.js#L979-L982)

**Comment by Tsubakura** [comment] 2017-02-02 00:39
![image](https://cloud.githubusercontent.com/assets/20300876/22532564/2d2527e0-e8e8-11e6-99f7-ceb5e2cbe033.png)
Doesnt seem a huge problem, but it happens :P

**Comment by sinsinpub** [comment] 2017-02-02 02:55
lol, i don't think there is a huge help if only a screenshot pasted without process to reproduce the issue.

@nonsensed i had been intend to remove a limit condition to test those Cn PvP and submarines quests, and forgotten it... it should be fixed now by adding this condition as we only handle Bd5, Bd6 for now. no matter which is activated, the counter should be (looked seem) consistent with game's.

**Comment by Javran** [comment] 2017-02-07 22:19
reopening this issue because the fix is not working:

I sunk 3 transport at a time, the counter still end up being wrong, all related quests are activated:

![2017-02-07_170932_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/22713914/461c69ec-ed58-11e6-9321-d320a82bbf6d.jpg)

now that I think we've in some sense proved that an attempt on fixing this counter is error-prone and probably unnecessary, I strongly suggest either reverting #1436 or having an option for user to opt out from this feature.

**Closed** 2017-02-08 07:26 UTC

**Comment by sinsinpub** [comment] 2017-02-08 07:30
Not necessary to revert, just welcome to report the the reproduce method. it does be necessary because why is your Bd6 80%(4/5) not 50%(3/5), despite of only 3 APs sunk?

**Comment by Javran** [comment] 2017-02-08 12:03
@sinsinpub well, I've been keeping a blind eye on this, but since you really want to argue:

- even without your so-called "fix", the quest counter should have corrected itself by the time one enters the quest list, so how is this "fix" necessary? letting user see a seemed completed quest going back to 80%? would any user feel happy that way? or do you think by doing so more user will be aware of the devtools page - click-to-toggle quest state feature?
- before your "fix": https://github.com/KC3Kai/KC3Kai/blob/7550b27fda37a08bcfe97a3f11c5e4bb23c53916/src/library/objects/Quest.js#L103-L112 , after your "fix":  https://github.com/KC3Kai/KC3Kai/blob/595c53a08bfb6809a6dd46281266657c5e6428c9/src/library/objects/Quest.js#L106-L137 . tell me how could this complication be necessary for just 2 quests that can already fix themselves through auto-adjustment?
- #1436 is merged **WITHOUT CONFORMATION FROM ANYONE ELSE**. so tell me what's wrong with reverting a not-well tested PR?
- @nonsensed has reported the same bug way earlier than me, plus this issue, this is at least **THE THIRD TIME**, let me repeat, **THE THIRD TIME** you are dealing with the same problem. and what you did is pushing directly to master branch and call such thing a "fix" without going through any discussion / confirmation from others, **YET AGAIN**.
-  talking about you "fix": https://github.com/KC3Kai/KC3Kai/commit/b7407a13dad34556ee5c8dcd0e850b3974f6ea34 https://github.com/KC3Kai/KC3Kai/commit/d34f28b156484136744b8890d71e095fd1cf7f55 every time you just added a bunch of new variables and statements, have you really thought thoroughly about a proper fix? how can you make me or anyone else believe that you are really respecting whatever info available on wikiwiki or wikia rather than just randomly change stuff to pass tests? This is exactly why PR is useful to have extra eyes on things and you eluded it.

I know no one is making a living for maintaining an open source software, but please be professional.
