### ISSUE TITLE
Hourly lines show up too soon!

### ISSUE THREAD

**Issue by Kam0laZ** [KC3Kai/KC3Kai#1599] opened 2016-11-16 11:05 UTC
- Chrome version: 54.0.2840.99 (Official Build) m (32-bit)
- OS: Windows 7 Ultimate x64 SP1
- KC3 Kai version: 30.11.0 webstore

At about 2-3 minutes left to the hour (i.e. 13:57-13:58), the translated hourly line shows up. When the hour strikes (i.e. 14:00), the audio hourly line plays as expected, but there's no translated line showing up.
This happens in Frame mode.

PS: I've gone back to using Website mode, at least until the Game Play Scale setting, reported in my previous post, is fixed in Frame mode.
While I was using Frame mode yesterday, I've noticed this issue reported here. So here it is. Hope it's clear enough.

**Comment by dragonjet** [comment] 2016-11-16 14:53
duplicate of #1243

**Closed by dragonjet** 2016-11-16 14:53 UTC
